version: "3"
services:
    web:
        image: andremmerlo/docker-python:latest
        deploy:
            replicas: 5
            resouces:
                limits:
                    cpus: "0.1"
                    memory: 50M
                restart_policy:
                    condition: on-failure
                ports:
                  -  "80:80"
                networks:
                  -  webnet
networks:
webnet: